services:
  gcc:
    container_name: gcc-dev
    build:
      context: .
      dockerfile: ../Dockerfile
    tty: true
    working_dir: /workspace
    volumes:
      - .:/workspace
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
