services:
  gcc:
    container_name: gcc-dev
    image: s3igo/gcc:latest
    tty: true
    working_dir: /workspace
    volumes:
      - ..:/workspace
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
